version: "3"
services:
  php:
    build: php
    ports:
      - 8000:80
      - 8443:443
    volumes:
      - ./drupal:/app/html
     # - ./apache/drupal.conf:/etc/apache2/sites-enabled/drupal.conf
  
  #web: 
  #  build: apache
  #  ports:
  #    - 80:80
  #   - 443:443
  #  volumes:
  #    - ./apache/prestashop.conf:/etc/apache2/sites-enabled/prestashop.conf
  #    - ./prestashop:/app/prestashop
  #    - ./apache/wordpress.conf:/etc/apache2/sites-enabled/wordpress.conf
  #    - ./wordpress:/app/wordpress
  #    - ./apache/server.key:/etc/ssl/private/server.key
  #    - ./apache/server.pem:/etc/ssl/certs/server.pem      
#
  db:
    image: mysql 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123.
      MYSQL_DATABASE: presta
      MYSQL_USER: prestauser
      MYSQL_PASSWORD: abc123.
    volumes:
      - basedatos:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      #- PMA_ARBITRARY=1
      - PMA_HOST=db
  
volumes:
  basedatos:
     