version: "3"
services:
  #php:
  #  build: php
  #  ports:
  #    - 80:80
  #    - 443:443
  #  volumes:
  #    - ./drupal:/var/www/html
  #    - .php/drupal.conf:/
  web: 
    build: apache
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apache/prestashop.conf:/etc/apache2/sites-enabled/prestashop.conf
      - ./prestashop:/app/prestashop
      - ./apache/wordpress.conf:/etc/apache2/sites-enabled/wordpress.conf
      - ./wordpress:/app/wordpress
      

  db:
    image: mysql 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abc123.
      MYSQL_DATABASE: presta
      MYSQL_USER: prestauser
      MYSQL_PASSWORD: abc123.
    volumes:
      - basedatos:/var/lib/mysql
    
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_ARBITRARY=1
  
volumes:
  basedatos:
     